"""Bounded tangent-lattice search on V^2=f(x), using no known points.

For x=n/d^2 write w^2=F_d(n). Near n0, w is approximated by
beta+alpha*k, k=n-n0. Integer pairs (k,w) near that line are obtained
from the lattice generated by (C,round(S*alpha)) and (0,S), with
target (0,-round(S*beta)). Gauss reduction and bounded nearest-plane
enumeration generate candidates; every actual point is checked exactly.

This is a heuristic adaptation of local linear approximation/lattice search,
not an implementation of Elkies' complete projective enumeration. Neither
the sampled centres nor the bounded closest-vector search are exhaustive.
"""
from decimal import Decimal, localcontext, ROUND_FLOOR
from fractions import Fraction as Q
import math
import time

from geometry import invariants
from point_arithmetic import on_curve


def nearest(n, d):
    if d<0: n,d=-n,-d
    return (2*n+d)//(2*d)


def gauss_reduce(u, v):
    """Exact two-dimensional lattice reduction, preserving the lattice."""
    def dot(a,b): return a[0]*b[0]+a[1]*b[1]
    while True:
        if dot(v,v)<dot(u,u): u,v=v,u
        mu=nearest(dot(u,v),dot(u,u))
        if not mu: return u,v
        v=(v[0]-mu*u[0],v[1]-mu*u[1])


def tangent_candidates(a, n0, d, radius=4):
    """Return a small, exactly checked set from one coefficient-derived box."""
    a=list(map(int,a));b2,b4,b6=map(int,invariants(a));d2=d*d
    def polynomial(n): return 4*n**3+b2*d2*n*n+2*b4*d2*d2*n+b6*d2**3
    f=polynomial(n0)
    if f<=0: return [],{'tested':0,'width':0}
    f1=12*n0*n0+2*b2*d2*n0+2*b4*d2*d2
    f2=24*n0+2*b2*d2
    with localcontext() as ctx:
        ctx.prec=max(80,len(str(f))+60)
        root=Decimal(f).sqrt();slope=Decimal(f1)/(2*root)
        # A conservative centre-scale estimate, not an interval error bound.
        curvature=Decimal(abs(f2))/(2*root)+Decimal(f1*f1)/(4*Decimal(f)*root)
        width=2 if not curvature else int((1/(8*curvature))**(Decimal(1)/3))
        width=max(2,min(1<<32,width))
        scale=16*width**4;horizontal=16*width**2;bound=horizontal*width
        alpha=int((slope*scale).to_integral_value(rounding=ROUND_FLOOR))
        beta=int((root*scale).to_integral_value(rounding=ROUND_FLOOR))
    u,v=gauss_reduce((horizontal,alpha),(0,scale))
    determinant=u[0]*v[1]-u[1]*v[0]
    target=(0,-beta);unorm=u[0]*u[0]+u[1]*u[1]
    j0=nearest(u[0]*target[1]-u[1]*target[0],determinant)
    offsets=sorted(range(-radius,radius+1),key=lambda k:(abs(k),k))
    numerators={n0}
    for dj in offsets:
        j=j0+dj;tx=target[0]-j*v[0];ty=target[1]-j*v[1]
        i0=nearest(u[0]*tx+u[1]*ty,unorm)
        for di in offsets:
            i=i0+di;x=i*u[0]+j*v[0];y=i*u[1]+j*v[1]
            if abs(x)>bound or abs(y-target[1])>2*bound: continue
            if x%horizontal: raise ArithmeticError('Lattice reconstruction')
            numerators.add(n0+x//horizontal)
    found=[];tested=0
    for n in sorted(numerators):
        if math.gcd(n,d)!=1: continue
        value=polynomial(n);tested+=1
        if value<0: continue
        z=math.isqrt(value)
        if z*z!=value: continue
        yn=-z-a[0]*n*d-a[2]*d**3
        if yn%2: continue
        point=(Q(n,d2),Q(yn,2*d**3))
        if not on_curve(list(map(Q,a)),point): raise ArithmeticError('Tangent candidate off curve')
        found.append(point)
    return found,{'tested':tested,'width':width}


def integer_cuberoot(n):
    lo,hi=0,1<<((n.bit_length()+2)//3)
    while lo+1<hi:
        mid=(lo+hi)//2
        if mid**3<=n: lo=mid
        else: hi=mid
    return lo


def search(a, centres=(), seconds=2, max_boxes=1024):
    """Sample centres/scales from the equation; at most one CPU and max_boxes."""
    a=list(map(int,a));start=time.perf_counter();deadline=start+seconds
    scale=max(1,abs(a[1]),math.isqrt(abs(a[3])),integer_cuberoot(abs(a[4])))
    def positions():
        yield from map(int,centres)
        yield 0
        for level in range(9):
            denominator=1<<level
            for numerator in sorted(range(-2*denominator,4*denominator+1),key=lambda n:(abs(n),n)):
                if level and numerator%2==0: continue
                yield nearest(numerator*scale,denominator)
    points={};seen=set();tested=0;boxes=0;max_width=0
    for centre in positions():
        for d in (1,2,3,4,8,16):
            if time.perf_counter()>=deadline or boxes>=max_boxes:
                return list(points),{'seconds':time.perf_counter()-start,'boxes':boxes,
                    'tested':tested,'max_width':max_width,'bounded_heuristic':True}
            n0=centre*d*d
            if (n0,d) in seen: continue
            seen.add((n0,d));boxes+=1
            found,stats=tangent_candidates(a,n0,d)
            tested+=stats['tested'];max_width=max(max_width,stats['width'])
            for point in found: points[point]=True
            if points:
                return list(points),{'seconds':time.perf_counter()-start,'boxes':boxes,
                    'tested':tested,'max_width':max_width,'bounded_heuristic':True}
    return list(points),{'seconds':time.perf_counter()-start,'boxes':boxes,
                        'tested':tested,'max_width':max_width,'bounded_heuristic':True}
